README.md
I thought I'd add some bare-bones instructions, what do you think?
=> Basic instructions for running

README.md, geforcenow-electron.desktop
- Added keywords to the Linux desktop launcher
- Updated the README file
=> Added keywords to the Linux desktop launcher

package-lock.json, package.json, scripts/main.js
- Removed the custom ``( Shift + ` )`` hotkey for toggling Fullscreen mode
Fixes part of #20 
Fixes #25
=> Removed the fullscreen custom hotkey

geforcenow-electron.desktop
- Fixed the desktop launcher category
=> Fixed the desktop launcher category

README.md, package-lock.json, package.json, scripts/main.js
- Fixed the full-screen mode not toggling correctly
- Changed the full-screen hotkey to `Super + F`
=> Fullscreen fix

package-lock.json, package.json, scripts/main.js
- Enabled hardware acceleration
- Upgraded to `electron` version `12.0.2`
- Upgraded to `electron-builder` version `22.10.5`
=> Hardware acceleration

package.json, scripts/main.js
- Fixed the login not working after the latest update
- Fixed the GFN window being fullscreen after exiting a fullscreen game
=> Fixed login issues

README.md, package-lock.json, package.json
- Upgraded `electron` from version `12.0.2` to `12.0.5`
- Added an AUR package badge in the readme
=> Maintenance: Update to the latest electron version

LICENSE.md, package.json
- Switched license to `GPL-3.0`
=> Switched license to GPL v3

package-lock.json, package.json
- Upgraded to electron 15.3.0
- Updated the dependencies
=> Upgraded to electron 15.3.0

scripts/main.js
- Arguments to spoof ChromeOS / Windows user agents
- Disable feature for prevent leaking of real user agent
=> Arguments to spoof ChromeOS / Windows user agents

scripts/main.js
You can just use F11 to do fullscreen instead of keybinds
=> Add F11 Fullscreen Support

README.md, scripts/main.js
The **README.md** needs to be updated because **Super + M** doesn't toggle microphone **CTRL + M** toggles the microphone  
**ALT + F4 / F4**: Shuts down app incase of the app not responding or its broken
**F12**: Toggles chrome dev tools
This has been ALL fully tested and works 100% fine
=> Shortcuts & Update README.md

README.md, package.json, scripts/main.js, scripts/rpc.js
I notice your lacking Discord RPC support so I decided why not add it
I know the icon isn't the best but atleast it works for now
=> Discord RPC

README.md, package-lock.json, package.json, scripts/rpc.js
=> Fix DiscordRPC errors

package-lock.json, package.json, scripts/main.js
Updating Electron to 18.2.0 did indeed fix the Steam Deck controller not working. I tested it and it works perfect now.
=> Updated Electron to 18.2.0 for Steam Deck support.

scripts/main.js
=> Removed the deprecated `nativeWindowOpen` preference

README.md, package-lock.json, package.json, scripts/main.js, scripts/windowManager.js
=> New and more robust window management

package.json, scripts/main.js, scripts/shortcutManager.js
It works With Ctrl+Shift+P with selected game.
And DevTools rebinded to Ctrl+Shift+I for easy use.
=> Direct game launch and shortcut generator

package.json, scripts/main.js
=> Updated the user agents

package-lock.json, package.json
- Updated to electron `20.1.4`
- Fixed 4 vulnerabilities
=> Updated to the latest electron version

package-lock.json, package.json, scripts/main.js
This pull request is for this issue: https://github.com/hmlendea/gfn-electron/issues/224
fixes #224
I hope you can approve my pull request. If you want me to change anything or something like that, please let me know.
=> isDiscordRunning check

package-lock.json, package.json, scripts/main.js
This pull request is for this issue: https://github.com/hmlendea/gfn-electron/issues/226
fixes #226
I hope you can approve my pull request (it might be needed to approve first my previous pull request). If you want me to change anything or something like that, please let me know.
=> Identifying a possible stable 'use-gl' implementation across systems

scripts/windowManager.js
I tested this on my local machine and it works
My mouse doesnt escape while playing and exits when exited playing
=> Fixed the pointer lock

README.md
Reverts hmlendea/gfn-electron#258
=> Removed 'Maintainers Wanted' from the readme

package-lock.json, package.json, scripts/main.js
=> A fix for Hardware Video Decoding

scripts/main.js
=> Use the `--enable-accelerated-video-decode` flag
